"""Shared data models for WSB Agent.

Dataclasses used across ingestion, feature extraction, and signal generation.
"""

from __future__ import annotations

from typing import Any
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Post:
    """A Reddit submission from WallStreetBets."""

    id: str
    title: str
    body: str
    score: int
    upvote_ratio: float
    num_comments: int
    created_utc: datetime
    author: str | None = None
    url: str | None = None
    permalink: str | None = None

    @property
    def full_text(self) -> str:
        """Combined title and body text for NLP processing."""
        parts = [self.title]
        if self.body and self.body != "[removed]" and self.body != "[deleted]":
            parts.append(self.body)
        return " ".join(parts)


@dataclass
class Comment:
    """A Reddit comment from a WallStreetBets post."""

    id: str
    body: str
    score: int
    created_utc: datetime
    post_id: str
    author: str | None = None
    parent_id: str | None = None


@dataclass
class TickerMention:
    """A detected stock ticker mention in text."""

    ticker: str
    confidence: float  # 0.0 to 1.0
    source_text: str  # The text span where ticker was found
    context: str  # "dollar_sign" | "uppercase" | "cashtag"


@dataclass
class SentimentResult:
    """Sentiment analysis result for a text or ticker."""

    ticker: str
    score: float  # -1.0 (bearish) to 1.0 (bullish)
    label: str  # "bullish" | "bearish" | "neutral"
    compound: float  # VADER compound score
    mention_count: int = 0
    scores: list[float] = field(default_factory=list)  # Individual mention scores
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def avg_score(self) -> float:
        """Average sentiment score across all mentions."""
        if not self.scores:
            return self.score
        return sum(self.scores) / len(self.scores)


@dataclass
class AttentionMetrics:
    """Attention/momentum metrics for a ticker."""

    ticker: str
    mention_count: int
    mention_velocity: float  # Change in mentions per hour
    engagement_weighted_mentions: float  # Score-weighted mention count
    sentiment_weighted_mentions: float  # Sentiment-weighted mention count
    window_hours: int = 6


@dataclass
class MarketFeatures:
    """Market-side features for a ticker."""

    ticker: str
    current_price: float | None = None
    return_1d: float | None = None
    return_5d: float | None = None
    return_20d: float | None = None
    volatility_20d: float | None = None
    volume_change_ratio: float | None = None


@dataclass
class Signal:
    """A trading signal generated by the signal engine."""

    ticker: str
    composite_score: float  # -1.0 to 1.0
    action: str  # "BUY" | "SELL" | "HOLD"
    confidence: float  # 0.0 to 1.0
    components: dict[str, float] = field(default_factory=dict)
    reasoning: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)
